# -*- coding: utf-8 -*-
"""my first hello world program in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bywdqWohWVI5rpl4y2F7dVWALgb6HmuJ
"""

print("Hello World")

"""**bold text**"""